### ISSUE TITLE
Used too much CPU time on onVehicleEntityCollision()

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#144]
##### Spigot version: 1.12

<hr>

#### Problem or bug:

TrainCarts used too much CPU time while processing VehicleEntityCollision event, here is a profiler log screenshot:

![image](https://user-images.githubusercontent.com/841969/27804127-dc7ecb6c-605f-11e7-8ccb-9bc37fd7d3ef.png)

onVehicleEntityCollision used more than 60% CPU time and causing server lag, is there any improvement can be applyed on reflection works (which caused 40% CPU time)?

#### Expected behaviour:

Not use that much CPU.

#### Steps to reproduce:

I cannot ensure which part caused these works taking so much time, but use `/train list` command and get:

> 51 trains on the server (2 are moving)

But I think 2 moving trains should not take 60% CPU times.

cc @sntc06 @fntsrlike (who maintains the same server with me)

**Comment by bergerkiller** [comment]
It appears there is a Minecart that does not have a TrainCarts entity controller attached. As a result its creating a temporary controller to return in getController(), which appears to be bugged doing an expensive class generation call every time its fired. Bug is very likely in BKCommonLib

**Comment by david50407** [comment]
@bergerkiller as you said, if the minecart is not placed by player or TrainCarts (like dispenser), it won't be attached to TrainCarts, that will cause huge load on creating temporary controller.

How will this be fixed? Skip carts that not belongs to TrainCarts, or try to make carts by dispenser to be TrainCarts' cart?

**Comment by bergerkiller** [comment]
I will have to fix this in BKCommonLib. It should never generate a 'hook' of an arbitrary Entity in getController. That logic is completely wrong, since it should only ever happen in setController. This is probably an edge case that is never really tested.

It already skips non-tc controllers in onVehicleCollision...by doing getController() instanceof MinecartMember. I think you see the problem now :)

**Comment by david50407** [comment]
And we can listen to BlockDispenseEvent if dispenser placed a cart on a rail to attach it to TrainCarts, right?

**Comment by bergerkiller** [comment]
Actually, the problem is even different than I initially thought. Its not that its hooking the entity; it's hooking itself. This has to do with the ClassHook which has a 'base' field, which is a hooked version of itself. This is a bug in Mountiplex, not BKCommonLib nor TrainCarts. It should be caching these generated classes of itself.

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/controller/EntityController.java#L41

https://github.com/bergerhealer/Mountiplex/blob/master/src/main/java/com/bergerkiller/mountiplex/reflection/ClassHook.java#L30

I think it should already replace all traincarts when 'all minecarts are traincarts' is set to true in the config. If not, then handling BlockDispenseEvent should mitigate it at least for that case.

**Comment by bergerkiller** [comment]
I've made relevant changes to Mountiplex that should at the very least reduce the huge performance loss you are seeing.

https://ci.mg-dev.eu/job/BKCommonLib/133/

**Comment by sntc06** [comment]
Hi,

I tried the above new version but it seems it improved just by a little. The TPS is now around 6 or 7 around problematic area of the map.
I got the profile snapshot with VisualVM, you can take a look if you want.

http://imgur.com/a/lvbPT

Profile: https://www.dropbox.com/s/c5g5f3lrpm9895y/profile2.nps?dl=0

Now it seems to spend time in `com.bergerkiller.bukkit.common.internal.hooks.EntityHook.<init>()`

Thanks for the work again.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/hooks/EntityHook.java#L24

This is debugging to later trace who tried to create the Entity Controller when its later bound, but in this case it's slowing down. Retrieving a stack trace this often obviously does not help. I will disable this and make sure this trace is only created inside setController.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/135/

There may be a new hotspot, but the big problems should now be fixed.

**Comment by sntc06** [comment]
We installed the new BKCommonLib, it seems improved, but not by much.
I think maybe it is really caused by the excessive amount of minecarts, and perhaps this cannot be improved anymore :(

Profile: https://www.dropbox.com/s/23406y1ydjhasf1/profile3.nps?dl=0
Image: https://www.dropbox.com/s/2rejgm8x9b7an2b/profile3.png?dl=0

**Comment by bergerkiller** [comment]
There are ways to make it better. It has to do with this issue ticket I wrote a few days ago
https://github.com/bergerhealer/Mountiplex/issues/7

There is a very easy way to fix it, but getController() is used a lot and I want to make sure this is fixed, instead of patching around it. I'll keep working on reducing the issues.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/137/
https://ci.mg-dev.eu/job/TrainCarts/63/

This has many new goodies and a way to avoid creating a DefaultEntityController that causes most of the lag. There will probably still be some hotspot in CommonEntity.get(), I'd be interested in seeing the full details of that if it still poses problems.

**Comment by sntc06** [comment]
We tried the new build, and the TPS is massively improved.
Even in most densed area filled with minecarts in our server, TPS still have a decent 16~18.
Thanks for all the great work you've done!

I attach the final profiling snapshot for your reference.
Profile: https://www.dropbox.com/s/ttsr6sh8gq4643j/profile4.nps?dl=0
Image: https://www.dropbox.com/s/yjags8ykjmxamfd/profile4.png?dl=0

**Comment by david50407** [comment]
It actually imporved the TPS, but there's a strange thing:

Although this patch gains more TPS on server, but when I'm around these carts, my client strats dropping FPS to around 10.
But without TrainCarts, client gets back to normal FPS.

I don't know the connection between TrainCarts and the client, it's wired.

**Comment by bergerkiller** [comment]
@sntc06 
Converters! Of course its them. Most of the places it does not use input converters because it has to look up the type it converts from. I'll have to replace it so it avoids that lookup in that particular case.

@david50407 
This can only have to do with the network controller. What happens when you disable this network controller in the TrainCarts configuration? It may be generating too many movement update (packets). This is hard to see visually.

**Comment by bergerkiller** [comment]
This may help to squeeze out that last bit of performance drop:
https://ci.mg-dev.eu/job/BKCommonLib/139/

Size a bit bigger because of unrelated additions (runtime codegen) presently unused.

**Comment by david50407** [comment]
@bergerkiller this BKC works good and lift TPS to around 20

**Comment by bergerkiller** [comment]
Closing this ticket now the main issues have been fixed. If new performance problems pop up a new one can be made.
