### ISSUE TITLE
Elevator - Config is missing

### ISSUE THREAD

**Issue by JCSweetHeart** [bergerhealer/TrainCarts#383]
##### Spigot version: 1.16.1

<hr>

**Comment by JCSweetHeart** [comment]
Problem is fixed - but is a good Think when you configurable that in the Configfile please.
-----

I must only Rewrite the Sign again with follow Thinks

Linie 1: [train]
Linie 2: elevator
Linie 3: (blank)
Linie 4: (blank)
---

Now its work, maybe a Bug when i updatet it to the New Version (but im not sure about that), i let this Issues for the moment open while the Elevator can`t find into the Configfile, but the Elevator - Bug is fixed.

**Comment by bergerkiller** [comment]
Just to clarify, the elevator sign works as follows:
```
[train]
elevator up
2
```

Which will teleport the train up to the second elevator sign (it skips one). When the third line is omitted, it teleports up to the next elevator 'level'. You can also use 'elevator down' to go down. When omitted on the second line, the elevator defaults to 'up'.

Is more information needed, or does an issue still exist? Something was fixed again, but from your issue ticket it wasn't very clear to me what the issue was.

**Comment by bbayu123** [comment]
I'm just going to assume this as resolved unless otherwise
